### PR TITLE
Allow enabling interrupts before entry and pre-interrupt init functions

### PR DESCRIPTION
**Pull request by YuhanLiin**
Addresses #14 with a different design than the one proposed. Since we can't have multiple attributes coordinate with each other, I added new arguments to the `entry` macro to achieve the desired semantics. I'll add `trybuild` tests once this design is finalized.

### CODE REVIEW

**Comment by cr1901** [comment]
## `CriticalSection` Token While Interrupts Are Enabled!

I think passing an argument back to main is unsound as-is, as this compiles from `msp430-quickstart` (with the relevant patch to `msp430-rt` in `Cargo.toml`):

```
#![no_main]
#![no_std]

extern crate panic_msp430;

use msp430::asm;
use msp430_rt::entry;

#[allow(unused)]
use msp430g2553;

fn arg(cs: msp430::interrupt::CriticalSection) -> msp430::interrupt::CriticalSection {
    /* initialize hardware */
    cs
}

#[entry(interrupt_enable(pre_interrupt = arg))]
fn main(_cs: msp430::interrupt::CriticalSection) -> ! {
    // Oops, we have a CriticalSection token when interrupts are enabled!

    asm::nop();
    loop {
    }
}

#[no_mangle]
extern "C" fn abort() -> ! {
    panic!();
}
```

I wonder if there's a way to examine recursively whether the type you pass out of the pre-entry init either borrows or owns _any_ `CriticalSection` tokens.

## Passing Data Out Of Init But Not To Main
Additionally, while the docs explicitly state (bold mine):

>The entry function can then **optionally** take a parameter of Type.

Does passing data out of the `pre-entry` function and not using it in main have any advantages? I feel like it could confuse people that the parameter is being ignored rather than a function sig mismatch. On the other hand, this correctly errors, so that's good:

```
#![no_main]
#![no_std]

extern crate panic_msp430;

use msp430::asm;
use msp430_rt::entry;

#[allow(unused)]
use msp430g2553;

fn arg(cs: msp430::interrupt::CriticalSection) -> msp430::interrupt::CriticalSection {
    /* initialize hardware */
    cs
}

#[entry(interrupt_enable(pre_interrupt = arg))]
fn main(_cs: u8) -> ! {

    asm::nop();
    loop {
    }
}

#[no_mangle]
extern "C" fn abort() -> ! {
    panic!();
}
```

```
William@DESKTOP-H0PMN4M MINGW64 ~/Projects/MSP430/msptest/msp430-int
$ cargo build --release --target=msp430-none-elf -Zbuild-std=core
   Compiling msp430-int v0.1.0 (C:\msys64\home\William\Projects\MSP430\msptest\msp430-int)error[E0308]: mismatched types
  --> src\main.rs:17:1
   |
17 | #[entry(interrupt_enable(pre_interrupt = arg))]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found struct `CriticalSection`
   |
   = note: this error originates in the attribute macro `entry` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `msp430-int` due to previous error
```

**Comment by YuhanLiin** [comment]
After some dark wizardry, I managed to (hopefully) banish the unsoundness with returning CriticalSections from `init`.

>Does passing data out of the pre-entry function and not using it in main have any advantages? I feel like it could confuse people that the parameter is being ignored rather than a function sig mismatch.
>
The main use case is for pre-entry functions that return nothing. In that case we want an entry signature of `main()`, but without this feature the signature would need to be `main(_: ())`, since `()` is technically the pre-entry return type. I have to make the entry parameter optional for all cases since the macro can't check if the pre-entry function returns nothing. In the case where pre-entry does return something, having no sig mismatch error, but if the main function needed to use the return value of pre-entry then another error would have popped up anyways.

By the way, are the macro argument names fine? If we can finalize the structure and naming of the macro arguments then I can add more comprehensive compile tests.

**Comment by cr1901** [comment]
@YuhanLiin Okay, this all looks good to me. Two comments re: documentation, that I'm not exactly sure how to handle yet:

1. I think I'd like "return value from init not being used in main is not an error" to be documented in more detail, since it can be surprising to those who don't know how the `entry` proc macro works. Perhaps something like you previously said:
   >I have to make the entry parameter optional for all cases since the macro can't check if the pre-entry function returns nothing. In the case where pre-entry does return something, having no sig mismatch error, but if the main function needed to use the return value of pre-entry then another error would have popped up anyways.

   I might summarize this as the following in the docs:
   > A function marked with the `entry` attribute is allowed to take no input parameters even if the pre-entry function returns a value. This is because the proc-macro code generation splits extracting the return value from pre-entry (_if any_) and supplying an input value to `entry` (_if any_) into separate steps.

2. I'd also like to explain how we prevent a `CriticalSection` from being returned. I don't particularly care for the error generated as-is if someone _tries_ to return a `CriticalSection` anyway:

```
William@DESKTOP-H0PMN4M MINGW64 ~/Projects/MSP430/msptest/msp430-int
$ cargo build --release
   Compiling msp430-int v0.1.0 (C:\msys64\home\William\Projects\MSP430\msptest\msp430-int)error[E0597]: `cs` does not live long enough
  --> src\main.rs:17:1
   |
17 | #[entry(interrupt_enable(pre_interrupt = arg))]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^-
   | |                                             |
   | |                                             `cs` dropped here while still borrowed
   | borrowed value does not live long enough
   | borrow later stored here
   |
   = note: this error originates in the attribute macro `entry` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0597`.
error: could not compile `msp430-int` due to previous error
```

Even with a macro-backtrace, this error doesn't tell me much.

FWIW, I created a minimal [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dc7dd607c300ebd2df3fde2260542237) snippet that could help to visualize both 1. and 2.

**Comment by cr1901** [comment]
>By the way, are the macro argument names fine? If we can finalize the structure and naming of the macro arguments then I can add more comprehensive compile tests.

Should we call it `pre_entry` or `pre_interrupt`? I think we should keep calling it `pre_interrupt`, even though throughout this PR I've been calling it "`pre-entry`" :D!

**Comment by YuhanLiin** [comment]
For 2, the error message applies to every function that takes a `CriticalSection`, so the documentation for it should be placed in the top level.

**Comment by YuhanLiin** [comment]
OK so with the `static mut` abstraction recursive calls for both entry and interrupts are unsound in general, since it leads to the creation of duplicate `&mut` references. This means both the "outer" and "inner" function names need to use random identifiers (so no more `no_mangle`). Can you also test that multiple invocations of `#[entry]` and identical `#[interrupt]` fails at link time? With `export_name` those cases no longer fail at compile time.

**Comment by cr1901** [comment]
>Can you also test that multiple invocations of #[entry] and identical #[interrupt] fails at link time?

These both do, in fact, fail at compile time when the relevant code of the below snippet is uncommented:

```rust
#![no_main]
#![no_std]
#![feature(abi_msp430_interrupt)]

extern crate panic_msp430;

use msp430_rt::entry;
use msp430g2553::interrupt;

fn arg(_cs: msp430::interrupt::CriticalSection) {
    /* initialize hardware */
}

#[entry(interrupt_enable(pre_interrupt = arg))]
fn main() -> ! {
    unimplemented!()
}

// #[entry(interrupt_enable(pre_interrupt = arg))]
// fn foo() -> ! {
//     unimplemented!()
// }

#[interrupt]
fn TIMER0_A1(_cs: CriticalSection) {
    unimplemented!()
}

// #[interrupt]
// fn TIMER0_A1(_cs: CriticalSection) {
//     unimplemented!()
// }

#[no_mangle]
extern "C" fn abort() -> ! {
    panic!();
}
```

## Uncomment `entry`

```cmd
PS C:\msys64\home\William\Projects\MSP430\msptest\msp430-int> cargo build --release
   Compiling msp430-int v0.1.0 (C:\msys64\home\William\Projects\MSP430\msptest\msp430-int)
error: symbol `main` is already defined
  --> src\main.rs:30:1
   |
30 | #[entry(interrupt_enable(pre_interrupt = arg))]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the attribute macro `entry` (in Nightly builds, run with -Z macro-backtrace for more info)


error: could not compile `msp430-int` due to previous error
```

## Uncomment `TIMER0_A1`

```cmd
PS C:\msys64\home\William\Projects\MSP430\msptest\msp430-int> cargo build --release
   Compiling msp430-int v0.1.0 (C:\msys64\home\William\Projects\MSP430\msptest\msp430-int)
error: symbol `TIMER0_A1` is already defined
  --> src\main.rs:40:1
   |
40 | #[interrupt]
   | ^^^^^^^^^^^^
   |
   = note: this error originates in the attribute macro `interrupt` (in Nightly builds, run with -Z macro-backtrace for more info)


error: could not compile `msp430-int` due to previous error
```

Does this output look reasonable to you? If so, I think we can merge this.

**Comment by YuhanLiin** [comment]
Error messages look fine to me.

**Pull request merged**
